name: "Release"

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        nix build .#SF-Mono-nerd-font-mono
        nix build .#SF-Mono-nerd-font-propo

    - name: Get current date
      id: date
      run: echo "DATE=$(date +%Y-%m-%d-%Hh%M)" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "${{ env.DATE }}"
        files: |
          result/share/fonts/truetype/*.ttf
          result/share/fonts/opentype/*.otf
